language: r
pandoc_version: 2.2.1
dist: focal
warnings_are_errors: false
services:
  - xvfb

branches:
  only:
    - dev
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin

before_install:
  - export DISPLAY=:99.0

script:
  - Rscript -e "qcbsRworkshops::build_workshops(update_template = TRUE, pdf = TRUE, script = TRUE)"

before_deploy:
  - mkdir public
  - cp README.md public
  - cp -r workshop* public/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  target_branch: master
  local_dir: public
  on:
    branch: dev
